#!/usr/bin/env node
// Generate lib/client.js, the browser half, from dictionaries/*.json.
//
// dsh loads client bundles through `window.__ModuleLoader__.load` and serves
// them as-is, so the output is plain JavaScript with no imports.
//
// Usage: node scripts/build.mjs [--verify]
//   --verify  exit 1 if lib/client.js is not what this script would write.

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
export const LANGUAGE = Object.freeze({ id: 'pt-BR', label: 'Português (Brasil)', fallback: 'en' })
const PLUGIN_ID = 'dsh-locale-pt-br'

/** @returns {Record<string, Record<string, string>>} namespace → key → text, sorted. */
export function readDictionaries(dir = join(ROOT, 'dictionaries'), { keepEmpty = false } = {}) {
  const out = {}
  for (const file of readdirSync(dir).filter((f) => f.endsWith('.json')).sort()) {
    const dict = JSON.parse(readFileSync(join(dir, file), 'utf8'))
    const entries = Object.entries(dict).filter(([, v]) => typeof v === 'string' && (keepEmpty || v.trim() !== ''))
    if (entries.length) out[file.slice(0, -'.json'.length)] = Object.fromEntries(entries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)))
  }
  return out
}

/** @param {Record<string, Record<string, string>>} dictionaries */
export function renderClient(dictionaries) {
  const lang = JSON.stringify(LANGUAGE.id)
  return `/**
 * Brazilian Portuguese (pt-BR) language pack for the DeepSeek Harness Web UI.
 *
 * Generated by scripts/build.mjs from dictionaries/*.json. Do not edit by hand.
 * No network access, no model calls, no browser storage: it only registers a
 * language and its dictionaries with dsh's locale service.
 */
window.__ModuleLoader__.load({
  id: ${JSON.stringify(PLUGIN_ID)},
  factory: () => {
    const module = { exports: {} }
    const exports = module.exports
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" })
    exports.inject = ["locale"]
    exports.apply = function apply(ctx) {
      ctx.effect(
        () => ctx.locale.addLanguage(${JSON.stringify(LANGUAGE)}),
        "${PLUGIN_ID}: language",
      )
      const dictionaries = ${JSON.stringify(dictionaries, null, 2).replace(/\n/g, '\n      ')}
      for (const ns of Object.keys(dictionaries)) {
        ctx.effect(
          () => ctx.locale.register(ns, ${lang}, dictionaries[ns]),
          "${PLUGIN_ID}: " + ns + " dictionary",
        )
      }
    }
    return module.exports
  },
})
`
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const target = join(ROOT, 'lib', 'client.js')
  const text = renderClient(readDictionaries())
  if (process.argv.includes('--verify')) {
    if (!existsSync(target) || readFileSync(target, 'utf8') !== text) {
      console.error('lib/client.js is out of date: run `npm run build`')
      process.exit(1)
    }
    console.log('lib/client.js is up to date')
  } else {
    writeFileSync(target, text)
    console.log(`wrote lib/client.js`)
  }
}
